# -*- coding: utf-8 -*-

"""
    onfonmediasmsgateway

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from onfonmediasmsgateway.decorators import lazy_property
from onfonmediasmsgateway.configuration import Configuration
from onfonmediasmsgateway.controllers.account_controller import AccountController
from onfonmediasmsgateway.controllers.template_controller import TemplateController
from onfonmediasmsgateway.controllers.sms_controller import SMSController
from onfonmediasmsgateway.controllers.group_controller import GROUPController
from onfonmediasmsgateway.controllers.campaign_controller import CampaignController


class OnfonmediasmsgatewayClient(object):

    config = Configuration

    @lazy_property
    def account(self):
        return AccountController()

    @lazy_property
    def template(self):
        return TemplateController()

    @lazy_property
    def sms(self):
        return SMSController()

    @lazy_property
    def group(self):
        return GROUPController()

    @lazy_property
    def campaign(self):
        return CampaignController()


    def __init__(self,
                 access_key='ACCESS_KEY',
                 api_key='API_KEY',
                 client_id='CLIENT_ID'):
        if access_key is not None:
            Configuration.access_key = access_key
        if api_key is not None:
            Configuration.api_key = api_key
        if client_id is not None:
            Configuration.client_id = client_id

